maintainer        "Cloudant - Joe Williams"
maintainer_email  "joe@cloudant.com"
license           "Proprietary - All Rights Reserved"
description       "Configures libcurl"
version           "0.1"
long_description  "Configures libcurl"