maintainer        "Cloudant"
maintainer_email  "support@cloudant.com"
license           "Apache 2.0"
description       "Configures libcurl"
version           "0.1"
long_description  "Configures libcurl"