maintainer        "Cloudant - Joe Williams"
maintainer_email  "joe@cloudant.com"
license           "Apache 2.0"
description       "Configures libmozjs"
version           "0.1"
long_description  "Configures libmozjs"
