maintainer        "Cloudant - Joe Williams"
maintainer_email  "joe@cloudant.com"
license           "Proprietary - All Rights Reserved"
description       "Configures aws elastic ip"
version           "0.1"
long_description  "Configures aws elastic ip"
depends "heartbeat"
