maintainer        "Cloudant"
maintainer_email  "support@cloudant.com"
license           "Apache 2.0"
description       "Configures aws elastic ip"
version           "0.1"
long_description  "Configures aws elastic ip"
depends "heartbeat"
