maintainer        "Cloudant - Joe Williams"
maintainer_email  "joe@cloudant.com"
license           "Apache 2.0"
description       "Configures bigcouch"
version           "0.1"
long_description  "Configures bigcouch"
depends "libicu42"
depends "libmozjs_1.9.2"
depends "runit"
depends "libcurl"