maintainer        "Cloudant"
maintainer_email  "support@cloudant.com"
license           "Apache 2.0"
description       "Configures bigcouch"
version           "0.1"
long_description  "Configures bigcouch"
depends "libicu"
depends "spidermonkey"
depends "runit"
depends "libcurl"
